//! Embedded CLDR locale tables (`no_std`, no `alloc`).
//!
//! The locale formatter data (number symbols/patterns, list connectors,
//! relative-time strings, currency symbols) is generated by the offline codegen
//! into flat binary blobs committed under `src/cldr/` and embedded here with
//! [`include_bytes!`]. Because the data is just bytes, this layer has no
//! dependency on the (alloc-only) formatter runtime types and compiles in every
//! configuration; only the formatting functions that build `String`s need
//! `alloc`.
//!
//! Blob layout (little-endian): `[u16 count]` then `count` records of
//! `[u8 key_len][key][u16 payload_len][payload]`. Within a payload a string is
//! `[u8 len][bytes]` and an optional string uses a leading `0xFF` for `None`.
//!
//! Tables that need finer feature gating than "one blob, one feature", or that
//! repeat enough strings for a per-record blob to be the wrong shape, are
//! emitted as Rust instead — see [`generated`].
//!
//! The whole module is `no_std`/no-`alloc` and always compiled; its accessors
//! are unused when the (alloc-gated) formatters are not built.
#![allow(dead_code)]

/// Codegen output that is Rust rather than a blob: `const fn` + `match` lookups,
/// like `crate::unicode::generated`. A blob is all-or-nothing, so data that only
/// some builds want (the narrow unit width, the non-`latn` numbering-system
/// symbols, the range patterns) lives here, where `#[cfg]` can drop individual
/// match arms.
///
/// Three tables are here for the other reason: `tz_names`, `lists` and
/// `relative` are wide enough that a `match` costs several times the strings it
/// holds, and their strings repeat heavily across locales, so they are
/// deduplicated string arenas plus index arrays. The blob format keys one opaque
/// payload per locale and cannot share a string between two of them; interning
/// is what keeps `relative`'s eight units × three widths to 2.5× the bytes its
/// seven units × one width used to cost.
pub(crate) mod generated;

// ---- Shared formatter record types (plain data, borrowing from the blobs). ----

/// A resolved CLDR number pattern (affixes + grouping / fraction-digit counts).
///
/// The struct is `#[non_exhaustive]`: it is a view onto the embedded CLDR
/// tables, which gain fields as the data does, so it is obtained from the
/// crate rather than constructed.
#[derive(Debug, Clone, Copy)]
#[non_exhaustive]
pub struct Pattern {
    /// Literal text before the number.
    pub prefix: &'static str,
    /// Literal text after the number (for percent/currency, the sign/symbol).
    pub suffix: &'static str,
    /// Minimum integer digits.
    pub min_int: u8,
    /// Minimum fraction digits.
    pub min_frac: u8,
    /// Maximum fraction digits.
    pub max_frac: u8,
    /// Primary (rightmost) grouping size, or 0 for no grouping.
    pub primary_group: u8,
    /// Secondary grouping size (e.g. 2 for Indian `#,##,##0`).
    pub secondary_group: u8,
}

/// The number symbols and patterns for one locale in one numbering system.
///
/// CLDR keys these under `symbols-numberSystem-<ns>` / `decimalFormats-…`, and
/// the blocks genuinely differ per system: `ar`'s `arab` decimal separator is
/// U+066B while its `latn` one is `.`, and `te` groups Indian-style in `latn`
/// but not in `telu`.
///
/// The struct is `#[non_exhaustive]`: it is a view onto the embedded CLDR
/// tables, which gain fields as the data does, so it is obtained from the crate
/// rather than constructed.
#[derive(Debug, Clone, Copy)]
#[non_exhaustive]
pub struct NumberSpec {
    /// Decimal separator.
    pub decimal: &'static str,
    /// Grouping separator.
    pub group: &'static str,
    /// Minus sign.
    pub minus: &'static str,
    /// Plus sign.
    pub plus: &'static str,
    /// Percent sign.
    pub percent: &'static str,
    /// The "not a number" placeholder (`en` `"NaN"`, `ar` `"ليس رقمًا"`).
    pub nan: &'static str,
    /// The infinity placeholder (`"∞"` in every vendored locale).
    pub infinity: &'static str,
    /// CLDR `numbers/minimumGroupingDigits`: how many digits must sit before the
    /// first group separator before grouping is used at all. `1` in `en`/`de`,
    /// `2` in `pl`/`es`/`et`/`lv`, which is why those render `1000` unseparated
    /// but `10000` grouped. A property of the locale, not of the system.
    pub min_grouping: u8,
    /// The standard decimal pattern.
    pub dec: Pattern,
    /// The standard percent pattern.
    pub pct: Pattern,
}

/// The four CLDR list connector patterns of one `type` × `style` combination
/// (each contains `{0}` and `{1}`).
///
/// The struct is `#[non_exhaustive]`: it is a view onto the embedded CLDR
/// tables, which gain fields as the data does, so it is obtained from the
/// crate rather than constructed.
#[derive(Debug, Clone, Copy)]
#[non_exhaustive]
pub struct ListPatterns {
    /// Joins the first two items of a 3+ list.
    pub start: &'static str,
    /// Joins an accumulated head with the next middle item.
    pub middle: &'static str,
    /// Joins the accumulated head with the final item.
    pub end: &'static str,
    /// Joins exactly two items.
    pub two: &'static str,
}

/// CLDR relative-time strings for one unit at one width — the `day-short`
/// block, say. `past`/`future` are indexed by the `PluralCategory` discriminant.
///
/// The struct is `#[non_exhaustive]`: it is a view onto the embedded CLDR
/// tables, which gain fields as the data does, so it is obtained from the
/// crate rather than constructed.
#[derive(Debug, Clone, Copy)]
#[non_exhaustive]
pub struct RelUnit {
    /// CLDR's `relative-type-<n>` literals — what ECMA-402 `numeric: "auto"`
    /// substitutes for a small offset — for offsets −2..=+3, indexed
    /// `offset + 2`: `"the day before yesterday"`, `"yesterday"`, `"today"`,
    /// `"tomorrow"`, … Most units define only −1/0/+1, and some only 0. Read it
    /// through [`RelUnit::literal`] rather than indexing by hand.
    pub literals: [Option<&'static str>; 6],
    /// Past patterns ("{0} days ago") by plural category.
    pub past: [Option<&'static str>; 6],
    /// Future patterns ("in {0} days") by plural category.
    pub future: [Option<&'static str>; 6],
}

#[cfg(feature = "relative")]
impl RelUnit {
    /// The `numeric: "auto"` literal for a signed `offset` — `−1` is
    /// `"yesterday"` for `day` in `en` — or `None` where the locale defines
    /// none and the numeric pattern must be used instead.
    #[must_use]
    pub fn literal(&self, offset: i64) -> Option<&'static str> {
        let slot = offset.checked_sub(i64::from(generated::relative::MIN_OFFSET))?;
        self.literals.get(usize::try_from(slot).ok()?).copied()?
    }
}

/// Gregorian calendar names and patterns for one locale (full/long/medium/short
/// styles are indexed 0..4).
///
/// The struct is `#[non_exhaustive]`: it is a view onto the embedded CLDR
/// tables, which gain fields as the data does, so it is obtained from the crate
/// rather than constructed.
#[derive(Debug, Clone, Copy)]
#[non_exhaustive]
pub struct CalendarSpec {
    /// Wide month names (January…), indexed by month−1.
    pub months_wide: [&'static str; 12],
    /// Abbreviated month names (Jan…).
    pub months_abbr: [&'static str; 12],
    /// Wide weekday names (Sunday…), indexed Sun..Sat.
    pub days_wide: [&'static str; 7],
    /// Abbreviated weekday names (Sun…).
    pub days_abbr: [&'static str; 7],
    /// AM marker.
    pub am: &'static str,
    /// PM marker.
    pub pm: &'static str,
    /// Date patterns by style.
    pub date: [&'static str; 4],
    /// Time patterns by style.
    pub time: [&'static str; 4],
    /// Date+time combining patterns by style (`{1}` date, `{0}` time).
    pub datetime: [&'static str; 4],
    /// Narrow month names (J, F, M…), indexed by month−1.
    pub months_narrow: [&'static str; 12],
    /// Narrow weekday names (S, M, T…), indexed Sun..Sat.
    pub days_narrow: [&'static str; 7],
    /// Wide era names (Before Christ, Anno Domini), indexed 0 = BCE, 1 = CE.
    pub eras_wide: [&'static str; 2],
    /// Abbreviated era names (BC, AD).
    pub eras_abbr: [&'static str; 2],
    /// Narrow era names (B, A).
    pub eras_narrow: [&'static str; 2],
    /// Wide flexible day-period names, indexed by the day-period key order
    /// (midnight, noon, morning1, morning2, afternoon1, afternoon2, evening1,
    /// evening2, night1, night2); `None` where the locale has no such period.
    pub day_periods_wide: [Option<&'static str>; 10],
    /// Abbreviated flexible day-period names (same indexing).
    pub day_periods_abbr: [Option<&'static str>; 10],
    /// Narrow flexible day-period names (same indexing).
    pub day_periods_narrow: [Option<&'static str>; 10],
    /// Minute-resolution flexible day-period range rules: a packed list of
    /// `[u16 from_minute][u16 to_minute][u8 period_index]` records (each 5 bytes,
    /// non-wrapping, `from < to`). A minute-of-day falling in `[from, to)` maps to
    /// `period_index` (an index into the `day_periods_*` arrays). The `_at`
    /// midnight/noon points are applied by the caller at the exact instant.
    pub day_period_rules: &'static [u8],
    /// The `atTime` variant of [`CalendarSpec::datetime`] (UTS #35
    /// `<dateTimeFormat type="atTime">`), by style: the combining pattern to use
    /// when `{0}` is a *time of day* — `"{1} 'at' {0}"` in `en`, `"{1} klo {0}"`
    /// in `fi`, against a plain slot of `"{1}, {0}"`. It differs from `datetime`
    /// in 74 of the 101 vendored locales.
    pub datetime_at: [&'static str; 4],
}

impl CalendarSpec {
    /// The flexible day-period index for a `minute` of day (0..=1439) from the
    /// locale's CLDR range rules, or `0xFF` if no range covers it.
    #[cfg(feature = "datetime")]
    pub(crate) fn day_period_index(&self, minute: u16) -> u8 {
        let b = self.day_period_rules;
        let mut o = 0;
        while o + 5 <= b.len() {
            let from = u16::from_le_bytes([b[o], b[o + 1]]);
            let to = u16::from_le_bytes([b[o + 2], b[o + 3]]);
            let idx = b[o + 4];
            o += 5;
            if minute >= from && minute < to {
                return idx;
            }
        }
        0xFF
    }
}

// ---- Embedded blobs. ----

#[cfg(feature = "currency")]
const CURRENCY: &[u8] = include_bytes!("cldr/currency.bin");
#[cfg(feature = "currency")]
const CURRENCY_DIGITS: &[u8] = include_bytes!("cldr/currency_digits.bin");
#[cfg(feature = "displaynames")]
const DISPLAY_LANG: &[u8] = include_bytes!("cldr/display_languages.bin");
#[cfg(feature = "displaynames")]
const DISPLAY_TERR: &[u8] = include_bytes!("cldr/display_territories.bin");
#[cfg(feature = "datetime")]
const CALENDAR: &[u8] = include_bytes!("cldr/calendar.bin");
#[cfg(feature = "datetime")]
const SKELETONS: &[u8] = include_bytes!("cldr/skeletons.bin");
#[cfg(feature = "datetime")]
const INTERVALS: &[u8] = include_bytes!("cldr/intervals.bin");
#[cfg(feature = "locale")]
const LIKELY: &[u8] = include_bytes!("cldr/likely.bin");
#[cfg(feature = "locale")]
const ALIASES: &[u8] = include_bytes!("cldr/aliases.bin");
#[cfg(feature = "locale")]
const BCP47: &[u8] = include_bytes!("cldr/bcp47.bin");
#[cfg(feature = "spellout")]
const RBNF: &[u8] = include_bytes!("cldr/rbnf.bin");
#[cfg(feature = "number")]
const COMPACT: &[u8] = include_bytes!("cldr/compact.bin");
#[cfg(feature = "number")]
const NUMSYS_DIGITS: &[u8] = include_bytes!("cldr/numsys_digits.bin");
#[cfg(feature = "number")]
const ORDSUFFIX: &[u8] = include_bytes!("cldr/ordsuffix.bin");
#[cfg(feature = "collation")]
const COLLATION: &[u8] = include_bytes!("cldr/collation.bin");
#[cfg(feature = "calendars-extra")]
const ALT_CALENDARS: &[u8] = include_bytes!("cldr/alt_calendars.bin");
#[cfg(feature = "calendars-extra")]
const LUNISOLAR: &[u8] = include_bytes!("cldr/lunisolar.bin");
#[cfg(feature = "calendars-extra")]
const JAPANESE: &[u8] = include_bytes!("cldr/japanese.bin");
#[cfg(feature = "calendars-extra")]
const JAPANESE_HIST: &[u8] = include_bytes!("cldr/japanese_hist.bin");

/// The CLDR collation tailoring rule string for an exact (lowercased) locale
/// key, or `None`. Used by `unicode::collate::Tailoring::for_locale`.
#[cfg(feature = "collation")]
pub(crate) fn collation_rule(lang: &str) -> Option<&'static str> {
    core::str::from_utf8(rbnf_like_payload(COLLATION, lang)?).ok()
}

/// Look up a `[u16 count]`-prefixed `(key, payload)` blob by exact key.
#[cfg(feature = "collation")]
fn rbnf_like_payload(blob: &'static [u8], lang: &str) -> Option<&'static [u8]> {
    let count = rd_u16(blob, 0);
    let mut o = 2;
    for _ in 0..count {
        let klen = blob[o] as usize;
        o += 1;
        let k = &blob[o..o + klen];
        o += klen;
        let plen = rd_u16(blob, o);
        o += 2;
        if k == lang.as_bytes() {
            return Some(&blob[o..o + plen]);
        }
        o += plen;
    }
    None
}

/// The ordinal suffix for `category` (0=zero…5=other) in an exact (lowercased)
/// locale key.
#[cfg(feature = "number")]
pub(crate) fn ordinal_suffix(lang: &str, category: usize) -> Option<&'static str> {
    let mut c = find(ORDSUFFIX, lang)?;
    let mut s = "";
    for i in 0..6 {
        let v = c.str();
        if i == category {
            s = v;
        }
    }
    Some(s)
}

/// The 10 digit glyphs of a numbering system (e.g. `"arab"` → `"٠١٢٣٤٥٦٧٨٩"`).
#[cfg(feature = "number")]
pub(crate) fn numbering_digits(system: &str) -> Option<&'static str> {
    find(NUMSYS_DIGITS, system).map(|mut c| c.str())
}

/// Compact (short) decimal patterns for magnitudes 10³…10¹⁴ in an exact
/// (lowercased) locale key.
#[cfg(feature = "number")]
pub(crate) fn compact_patterns(lang: &str) -> Option<[&'static str; 24]> {
    let mut c = find(COMPACT, lang)?;
    Some(core::array::from_fn(|_| c.str()))
}

/// The raw RBNF payload bytes for an exact (lowercased) locale key (parsed by
/// the `spellout` module).
#[cfg(feature = "spellout")]
pub(crate) fn rbnf_payload(lang: &str) -> Option<&'static [u8]> {
    let count = rd_u16(RBNF, 0);
    let mut o = 2;
    for _ in 0..count {
        let klen = RBNF[o] as usize;
        o += 1;
        let k = &RBNF[o..o + klen];
        o += klen;
        let plen = rd_u16(RBNF, o);
        o += 2;
        if k == lang.as_bytes() {
            return Some(&RBNF[o..o + plen]);
        }
        o += plen;
    }
    None
}

/// The widest month list any [`AltCalSpec`] calendar names: Coptic, Ethiopic and
/// Hebrew have 13. Must match codegen's `ALT_MAX_MONTHS`.
pub const ALT_MAX_MONTHS: usize = 13;

/// Month names, era names and patterns for one non-lunisolar, non-Gregorian
/// calendar in one locale — the shape shared by every calendar in
/// `alt_calendars.bin` (Buddhist, Coptic, Ethiopic, Hebrew, Indian, Islamic,
/// Persian, ROC).
///
/// The month and era lists are fixed-size arrays with an explicit count rather
/// than slices, because the blob is read into a value on the stack; entries at or
/// past the count are `""` and must not be shown. See [`AltCalSpec::month`] and
/// [`AltCalSpec::era`], which apply the bounds.
///
/// The struct is `#[non_exhaustive]`: it is a view onto the embedded CLDR tables,
/// which gain fields as the data does, so it is obtained from the crate rather
/// than constructed.
#[derive(Debug, Clone, Copy)]
#[non_exhaustive]
pub struct AltCalSpec {
    /// Wide month names, indexed by month−1.
    pub months_wide: [&'static str; ALT_MAX_MONTHS],
    /// Abbreviated month names.
    pub months_abbr: [&'static str; ALT_MAX_MONTHS],
    /// Narrow month names (for most of these calendars CLDR's narrow form is the
    /// month *number*, but not in every locale, so it is stored).
    pub months_narrow: [&'static str; ALT_MAX_MONTHS],
    /// How many of the `months_*` entries are populated: 12, 13, or 0 when this
    /// calendar reuses the locale's Gregorian month names verbatim (Buddhist and
    /// ROC do, in every vendored locale — codegen checks rather than assumes).
    pub month_count: u8,
    /// The 1-based month that has a distinct name in a leap year (UTS #35
    /// `yeartype="leap"`), or 0 for none. Only Hebrew uses it: month 7 is "Adar"
    /// in a common year and "Adar II" in a leap year.
    pub leap_month: u8,
    /// That month's leap-year name in `[wide, abbreviated, narrow]` order; all
    /// `""` when `leap_month` is 0.
    pub leap_names: [&'static str; 3],
    /// Wide era names, indexed from [`AltCalSpec::era_base`] (e.g. Islamic
    /// 0 = `"Anno Hegirae"`, 1 = `"Before Hijrah"`; Coptic's only era is CLDR
    /// index 1, so `era_base` is 1 and this is `["Anno Martyrum", ""]`).
    pub eras_wide: [&'static str; 2],
    /// Abbreviated era names (e.g. `"AH"`/`"BH"`, `"AP"`).
    pub eras_abbr: [&'static str; 2],
    /// Narrow era names.
    pub eras_narrow: [&'static str; 2],
    /// The CLDR era index that `eras_*[0]` carries (0 for all but Coptic, whose
    /// single era is index 1).
    pub era_base: u8,
    /// How many of the `eras_*` entries are populated (1 or 2).
    pub era_count: u8,
    /// Date patterns by style (full/long/medium/short).
    pub date: [&'static str; 4],
}

impl AltCalSpec {
    /// The name of 1-based `month` at width `w` (0 = wide, 1 = abbreviated,
    /// 2 = narrow), or `None` if this calendar has no month of that number (or
    /// borrows the Gregorian ones — `month_count == 0`). `leap` selects the
    /// leap-year variant where the calendar has one.
    #[cfg(feature = "calendars-extra")]
    pub(crate) fn month(&self, month: u32, leap: bool, w: usize) -> Option<&'static str> {
        if month == 0 || month > u32::from(self.month_count) {
            return None;
        }
        if leap && u32::from(self.leap_month) == month {
            return Some(self.leap_names[w]);
        }
        let table = match w {
            0 => &self.months_wide,
            1 => &self.months_abbr,
            _ => &self.months_narrow,
        };
        Some(table[month as usize - 1])
    }

    /// The name of CLDR era index `era` at width `w` (0 = wide, 1 = abbreviated,
    /// 2 = narrow), or `None` if this calendar has no such era.
    #[cfg(feature = "calendars-extra")]
    pub(crate) fn era(&self, era: u32, w: usize) -> Option<&'static str> {
        let i = era.checked_sub(u32::from(self.era_base))?;
        if i >= u32::from(self.era_count) {
            return None;
        }
        let table = match w {
            0 => &self.eras_wide,
            1 => &self.eras_abbr,
            _ => &self.eras_narrow,
        };
        Some(table[i as usize])
    }
}

/// Names + patterns for calendar `cal` (a BCP-47 `ca-` key such as `"islamic"`)
/// in an exact (lowercased) locale key.
#[cfg(feature = "calendars-extra")]
pub(crate) fn alt_cal_spec(cal: &str, lang: &str) -> Option<AltCalSpec> {
    let mut c = find2(ALT_CALENDARS, cal, lang)?;
    let month_count = c.u8();
    let n = month_count as usize;
    let mut months = [[""; ALT_MAX_MONTHS]; 3];
    for w in &mut months {
        for slot in w.iter_mut().take(n) {
            *slot = c.str();
        }
    }
    let leap_month = c.u8();
    let leap_names = if leap_month == 0 {
        [""; 3]
    } else {
        [c.str(), c.str(), c.str()]
    };
    let era_base = c.u8();
    let era_count = c.u8();
    let mut eras = [[""; 2]; 3];
    for w in &mut eras {
        for slot in w.iter_mut().take(era_count as usize) {
            *slot = c.str();
        }
    }
    Some(AltCalSpec {
        months_wide: months[0],
        months_abbr: months[1],
        months_narrow: months[2],
        month_count,
        leap_month,
        leap_names,
        eras_wide: eras[0],
        eras_abbr: eras[1],
        eras_narrow: eras[2],
        era_base,
        era_count,
        date: core::array::from_fn(|_| c.str()),
    })
}

/// Lunisolar-calendar names + patterns for one locale — the shape shared by the
/// Chinese and Korean (`dangi`) calendars: the 60 sexagenary (cyclic) year names
/// (the `U` field), numeric month names in three widths, the leap-month marker
/// pattern in four widths and the four date patterns. Neither calendar has eras
/// in CLDR.
///
/// The struct is `#[non_exhaustive]`: it is a view onto the embedded CLDR tables,
/// which gain fields as the data does, so it is obtained from the crate rather
/// than constructed.
#[derive(Debug, Clone, Copy)]
#[non_exhaustive]
pub struct ChineseCalSpec {
    /// The 60 sexagenary cyclic year names, indexed by the 1-based
    /// stem-branch number minus 1 (e.g. index 40 → 甲辰 / `jia-chen`). The CLDR
    /// widths are identical, so this one set serves every `U` width.
    pub cyclic: [&'static str; 60],
    /// Wide numeric month names (e.g. `"正月"` / `"First Month"`), indexed month−1.
    pub months_wide: [&'static str; 12],
    /// Abbreviated numeric month names (e.g. `"Mo1"`), indexed month−1.
    pub months_abbr: [&'static str; 12],
    /// Narrow numeric month names (e.g. `"1"`), indexed month−1.
    pub months_narrow: [&'static str; 12],
    /// Wide leap-month marker pattern (contains `{0}`, e.g. `"闰{0}"` / `"{0}bis"`).
    pub leap_wide: &'static str,
    /// Abbreviated leap-month marker pattern.
    pub leap_abbr: &'static str,
    /// Narrow leap-month marker pattern (e.g. `"{0}b"`).
    pub leap_narrow: &'static str,
    /// The marker used with a *numeric* month, CLDR's separate `numeric/all`
    /// entry (e.g. `"{0}bis"`, so month 2 of a leap year prints `"2bis"`).
    pub leap_numeric: &'static str,
    /// Date patterns by style (full/long/medium/short).
    pub date: [&'static str; 4],
}

impl ChineseCalSpec {
    /// The leap-month marker pattern at width `w` (0 = wide, 1 = abbreviated,
    /// 2 = narrow, 3 = numeric).
    #[cfg(feature = "calendars-extra")]
    pub(crate) fn leap(&self, w: usize) -> &'static str {
        match w {
            0 => self.leap_wide,
            1 => self.leap_abbr,
            2 => self.leap_narrow,
            _ => self.leap_numeric,
        }
    }
}

/// Lunisolar-calendar names + patterns for calendar `cal` (`"chinese"` or
/// `"dangi"`) in an exact (lowercased) locale key.
#[cfg(feature = "calendars-extra")]
pub(crate) fn chinese_spec(cal: &str, lang: &str) -> Option<ChineseCalSpec> {
    let mut c = find2(LUNISOLAR, cal, lang)?;
    Some(ChineseCalSpec {
        cyclic: core::array::from_fn(|_| c.str()),
        months_wide: core::array::from_fn(|_| c.str()),
        months_abbr: core::array::from_fn(|_| c.str()),
        months_narrow: core::array::from_fn(|_| c.str()),
        leap_wide: c.str(),
        leap_abbr: c.str(),
        leap_narrow: c.str(),
        leap_numeric: c.str(),
        date: core::array::from_fn(|_| c.str()),
    })
}

/// Japanese-calendar data for one locale: the 5 modern eras (Meiji, Taishō,
/// Shōwa, Heisei, Reiwa) in three widths and the four date patterns. The Japanese
/// calendar shares the Gregorian month and weekday names, so only the era and the
/// (year-within-era) year field differ; those names are taken from the Gregorian
/// [`CalendarSpec`] by the caller.
#[derive(Debug, Clone, Copy)]
pub struct JapaneseCalSpec {
    /// Wide era names (`eraNames`), indexed by modern-era number (0 = Meiji …
    /// 4 = Reiwa). Used for the `GGGG` field width.
    pub eras_wide: [&'static str; 5],
    /// Abbreviated era names (`eraAbbr`); the `G`/`GG`/`GGG` field width.
    pub eras_abbr: [&'static str; 5],
    /// Narrow era names (`eraNarrow`, e.g. `"R"`); the `GGGGG` field width.
    pub eras_narrow: [&'static str; 5],
    /// Date patterns by style (full/long/medium/short). Every pattern carries a
    /// `G` (era) field.
    pub date: [&'static str; 4],
    /// Gannen bitmask: bit `i` (full=0, long=1, medium=2, short=3) is set when
    /// that style's year field uses the `jpanyear` numbering system, i.e. year 1
    /// of an era prints as 元 (gannen) instead of `1`.
    pub gannen: u8,
}

/// Japanese-calendar names + patterns for an exact (lowercased) locale key.
#[cfg(feature = "calendars-extra")]
pub(crate) fn japanese_spec(lang: &str) -> Option<JapaneseCalSpec> {
    let mut c = find(JAPANESE, lang)?;
    Some(JapaneseCalSpec {
        eras_wide: core::array::from_fn(|_| c.str()),
        eras_abbr: core::array::from_fn(|_| c.str()),
        eras_narrow: core::array::from_fn(|_| c.str()),
        date: core::array::from_fn(|_| c.str()),
        gannen: c.u8(),
    })
}

/// Number of pre-Meiji historical Japanese era names in `japanese_hist.bin`
/// (CLDR era indices 0 = Taika .. 231 = Keiō); must match codegen's
/// `HIST_ERA_COUNT`.
#[cfg(feature = "calendars-extra")]
pub(crate) const HIST_ERA_COUNT: usize = 232;

/// The localized pre-Meiji nengō (era) name for CLDR era `index` (0..=231) in
/// an exact (lowercased) locale key, as `[wide, abbr, narrow]`, or `None` if the
/// locale is absent. See `emit_japanese_hist` for the blob layout.
#[cfg(feature = "calendars-extra")]
pub(crate) fn japanese_hist_eras(lang: &str, index: usize) -> Option<[&'static str; 3]> {
    if index >= HIST_ERA_COUNT {
        return None;
    }
    let b = JAPANESE_HIST;
    let nloc = rd_u16(b, 0);
    let mut o = 2;
    let mut setid: Option<usize> = None;
    for _ in 0..nloc {
        let klen = b[o] as usize;
        o += 1;
        let k = &b[o..o + klen];
        o += klen;
        let sid = rd_u16(b, o);
        o += 2;
        if k == lang.as_bytes() {
            setid = Some(sid);
        }
    }
    let setid = setid?;
    let nsets = rd_u16(b, o);
    o += 2;
    let table = o;
    let sets_base = table + nsets * 4;
    let set_off = rd_u32(b, table + setid * 4);
    let mut c = Cursor {
        b,
        o: sets_base + set_off,
    };
    let mut res = [""; 3];
    for slot in &mut res {
        for i in 0..HIST_ERA_COUNT {
            let s = c.str();
            if i == index {
                *slot = s;
            }
        }
    }
    Some(res)
}

/// The maximized locale for a likelySubtags key (e.g. `"en"` → `"en-Latn-US"`).
#[cfg(feature = "locale")]
pub(crate) fn likely_subtags(key: &str) -> Option<&'static str> {
    find(LIKELY, key).map(|mut c| c.str())
}

/// Look up a CLDR deprecated-subtag alias by its type-prefixed key and return
/// the replacement, or `None`. The 1-char prefix selects the alias kind: `'l'`
/// language / grandfathered whole tag, `'s'` script, `'t'` territory, `'v'`
/// variant (e.g. `"liw"` → `"he"`, `"sQaai"` → `"Zinh"`, `"tBU"` → `"MM"`). A
/// multi-subtag or one→many replacement is returned space-separated. This module
/// is alloc-free, so the caller (in `locale.rs`) builds the prefixed key.
#[cfg(feature = "locale")]
pub(crate) fn alias_lookup(prefixed_key: &str) -> Option<&'static str> {
    find(ALIASES, prefixed_key).map(|mut c| c.str())
}

/// Canonical replacement for a deprecated `-u-`/`-t-` extension type value, or
/// `None`. The key is `"<keyword>/<value>"` lowercased, e.g. `"ca/islamicc"` →
/// `"islamic-civil"`, `"ms/imperial"` → `"uksystem"`, `"m0/names"` → `"prprname"`.
/// The returned value keeps CLDR `-` subtag separators.
#[cfg(feature = "locale")]
pub(crate) fn bcp47_type_alias(keyword_and_value: &str) -> Option<&'static str> {
    find(BCP47, keyword_and_value).map(|mut c| c.str())
}

fn rd_u16(b: &[u8], o: usize) -> usize {
    u16::from_le_bytes([b[o], b[o + 1]]) as usize
}

#[cfg(feature = "calendars-extra")]
fn rd_u32(b: &[u8], o: usize) -> usize {
    u32::from_le_bytes([b[o], b[o + 1], b[o + 2], b[o + 3]]) as usize
}

/// A forward cursor over a record payload in a `'static` blob.
struct Cursor {
    b: &'static [u8],
    o: usize,
}
impl Cursor {
    fn u8(&mut self) -> u8 {
        let v = self.b[self.o];
        self.o += 1;
        v
    }
    fn u16(&mut self) -> usize {
        let v = rd_u16(self.b, self.o);
        self.o += 2;
        v
    }
    fn str(&mut self) -> &'static str {
        let n = self.u8() as usize;
        let s = &self.b[self.o..self.o + n];
        self.o += n;
        core::str::from_utf8(s).unwrap_or("")
    }
    fn opt(&mut self) -> Option<&'static str> {
        if self.b[self.o] == 0xFF {
            self.o += 1;
            None
        } else {
            Some(self.str())
        }
    }
    fn skip_opt(&mut self) {
        if self.b[self.o] == 0xFF {
            self.o += 1;
        } else {
            let n = self.b[self.o] as usize;
            self.o += 1 + n;
        }
    }
    /// Read a length-prefixed day-period rule list: a `[u8 count]` followed by
    /// `count` 5-byte records, returned as a raw slice (parsed lazily).
    fn dp_rules(&mut self) -> &'static [u8] {
        let n = self.u8() as usize * 5;
        let s = &self.b[self.o..self.o + n];
        self.o += n;
        s
    }
    fn pattern(&mut self) -> Pattern {
        Pattern {
            prefix: self.str(),
            suffix: self.str(),
            min_int: self.u8(),
            min_frac: self.u8(),
            max_frac: self.u8(),
            primary_group: self.u8(),
            secondary_group: self.u8(),
        }
    }
}

/// Locate the record for `key` and return a cursor at its payload.
fn find(blob: &'static [u8], key: &str) -> Option<Cursor> {
    let count = rd_u16(blob, 0);
    let mut o = 2;
    for _ in 0..count {
        let klen = blob[o] as usize;
        o += 1;
        let k = &blob[o..o + klen];
        o += klen;
        let plen = rd_u16(blob, o);
        o += 2;
        if k == key.as_bytes() {
            return Some(Cursor { b: blob, o });
        }
        o += plen;
    }
    None
}

/// Locate the record whose key is `"<a>/<b>"` and return a cursor at its payload.
///
/// The per-calendar tables are keyed by calendar *and* locale, and this module is
/// alloc-free, so the two halves are compared in place rather than concatenated
/// into a lookup key.
#[cfg(feature = "calendars-extra")]
fn find2(blob: &'static [u8], a: &str, b: &str) -> Option<Cursor> {
    let count = rd_u16(blob, 0);
    let mut o = 2;
    for _ in 0..count {
        let klen = blob[o] as usize;
        o += 1;
        let k = &blob[o..o + klen];
        o += klen;
        let plen = rd_u16(blob, o);
        o += 2;
        if k.len() == a.len() + 1 + b.len()
            && &k[..a.len()] == a.as_bytes()
            && k[a.len()] == b'/'
            && &k[a.len() + 1..] == b.as_bytes()
        {
            return Some(Cursor { b: blob, o });
        }
        o += plen;
    }
    None
}

/// Number symbols + patterns for an exact (lowercased) locale key in numbering
/// system `system`, through UTS #35 resource inheritance: the locale's own
/// `symbols-numberSystem-<system>` block, else **root's** for that system, else
/// the locale's `latn` block. Root only defines `arab` and `arabext`; every other
/// system aliases to `latn` with `source="locale"`, i.e. to this locale's.
#[cfg(feature = "number")]
pub(crate) fn number_spec(lang: &str, system: &str) -> Option<NumberSpec> {
    generated::numbers::spec(lang, system)
}

/// The plural category a range takes from its two ends' categories (CLDR
/// `pluralRanges.xml`), as `PluralCategory` discriminants. `en` `one`+`other` is
/// `other`, so a collapsed range reads "1–2 kilometers".
#[cfg(feature = "number-range")]
pub(crate) fn plural_range(lang: &str, start: usize, end: usize) -> usize {
    generated::numbers::plural_range(lang, start, end)
}

/// `(defaultNumberingSystem, otherNumberingSystems.native)` for an exact
/// (lowercased) locale key. Keyed by locale rather than by language: CLDR's
/// region files override the default alone (`ar-EG` is `arab`, `ar` is `latn`).
#[cfg(feature = "number")]
pub(crate) fn numbering_systems(lang: &str) -> Option<(&'static str, &'static str)> {
    generated::numbers::numbering_systems(lang)
}

/// The CLDR `miscPatterns` `(approximately, range)` forms for an exact
/// (lowercased) locale key.
#[cfg(feature = "number-range")]
pub(crate) fn misc_patterns(lang: &str) -> Option<(&'static str, &'static str)> {
    generated::numbers::misc_patterns(lang)
}

/// Table row for an exact (lowercased) locale key in the list-pattern tables.
#[cfg(feature = "list")]
pub(crate) fn list_locale(lang: &str) -> Option<u16> {
    generated::lists::locale_index(lang)
}

/// The list connectors of one ECMA-402 `type` × `style` combination, `kind`
/// being `type * 3 + width` (see `generated::lists`).
#[cfg(feature = "list")]
pub(crate) fn list_patterns(loc: u16, kind: usize) -> ListPatterns {
    let [start, middle, end, two] = generated::lists::patterns(loc, kind as u16);
    ListPatterns {
        start,
        middle,
        end,
        two,
    }
}

/// Table row for an exact (lowercased) locale key in the relative-time tables.
#[cfg(feature = "relative")]
pub(crate) fn relative_locale(lang: &str) -> Option<u16> {
    generated::relative::locale_index(lang)
}

/// The relative-time strings of one unit at one width.
#[cfg(feature = "relative")]
pub(crate) fn relative_unit(loc: u16, unit: usize, width: usize) -> RelUnit {
    let row = generated::relative::row(loc, unit as u16, width as u16);
    let at = |i: usize| generated::relative::str_at(row[i]);
    RelUnit {
        literals: core::array::from_fn(at),
        past: core::array::from_fn(|i| at(6 + i)),
        future: core::array::from_fn(|i| at(12 + i)),
    }
}

/// Standard currency pattern for an exact (lowercased) locale key.
#[cfg(feature = "currency")]
pub(crate) fn currency_pattern(lang: &str) -> Option<Pattern> {
    let mut c = find(CURRENCY, lang)?;
    Some(c.pattern())
}

/// The currency unit pattern (number + code/name, e.g. `"{0} {1}"`) for `lang`.
#[cfg(feature = "currency")]
pub(crate) fn currency_unit_pattern(lang: &str) -> Option<&'static str> {
    let mut c = find(CURRENCY, lang)?;
    let _ = c.pattern();
    Some(c.str())
}

/// Currency display forms `(symbol, narrow symbol, display name)` for `code` in
/// `lang` (exact lowercased key), if present.
#[cfg(feature = "currency")]
pub(crate) fn currency_forms(
    lang: &str,
    code: &str,
) -> Option<(&'static str, &'static str, &'static str)> {
    let mut c = find(CURRENCY, lang)?;
    let _ = c.pattern();
    let _ = c.str(); // unit pattern
    let n = c.u16();
    for _ in 0..n {
        let cd = c.str();
        let sym = c.str();
        let narrow = c.str();
        let name = c.str();
        if cd == code {
            return Some((sym, narrow, name));
        }
    }
    None
}

/// Default fraction digits for a currency code (2 if unknown).
#[cfg(feature = "currency")]
pub(crate) fn currency_digits(code: &str) -> u8 {
    match find(CURRENCY_DIGITS, code) {
        Some(mut c) => c.u8(),
        None => 2,
    }
}

/// Look up `code`'s display name in `display_locale`'s nested code→name table.
fn display_name(blob: &'static [u8], display_locale: &str, code: &str) -> Option<&'static str> {
    let mut c = find(blob, display_locale)?;
    let count = c.u16();
    for _ in 0..count {
        let cd = c.str();
        let name = c.str();
        if cd == code {
            return Some(name);
        }
    }
    None
}

/// Display name of language `code` in `display_locale` (exact lowercased keys).
#[cfg(feature = "displaynames")]
pub(crate) fn language_name(display_locale: &str, code: &str) -> Option<&'static str> {
    display_name(DISPLAY_LANG, display_locale, code)
}

/// The date pattern for a CLDR `skeleton` (e.g. `"yMMMd"`) in an exact
/// (lowercased) locale key; skeletons are matched case-sensitively.
#[cfg(feature = "datetime")]
pub(crate) fn skeleton_pattern(lang: &str, skeleton: &str) -> Option<&'static str> {
    display_name(SKELETONS, lang, skeleton)
}

/// The CLDR `intervalFormatFallback` string (e.g. `"{0} – {1}"`) for an exact
/// (lowercased) locale key.
#[cfg(feature = "datetime")]
pub(crate) fn interval_fallback(lang: &str) -> Option<&'static str> {
    find(INTERVALS, lang).map(|mut c| c.str())
}

/// The CLDR interval pattern for a `skeleton` (e.g. `"yMMMd"`) whose greatest
/// differing field is `field` (a CLDR field letter byte such as `b'y'`), in an
/// exact (lowercased) locale key. Skeletons are matched case-sensitively.
#[cfg(feature = "datetime")]
pub(crate) fn interval_pattern(lang: &str, skeleton: &str, field: u8) -> Option<&'static str> {
    let mut c = find(INTERVALS, lang)?;
    let _fallback = c.str();
    let count = c.u16();
    for _ in 0..count {
        let sk = c.str();
        let fcount = c.u8();
        let mut found: Option<&'static str> = None;
        for _ in 0..fcount {
            let letter = c.u8();
            let pat = c.str();
            if sk == skeleton && letter == field {
                found = Some(pat);
            }
        }
        if sk == skeleton {
            return found;
        }
    }
    None
}

/// Display name of region `code` in `display_locale`.
#[cfg(feature = "displaynames")]
pub(crate) fn region_name(display_locale: &str, code: &str) -> Option<&'static str> {
    display_name(DISPLAY_TERR, display_locale, code)
}

/// Gregorian calendar names + patterns for an exact (lowercased) locale key.
#[cfg(feature = "datetime")]
pub(crate) fn calendar_spec(lang: &str) -> Option<CalendarSpec> {
    let mut c = find(CALENDAR, lang)?;
    Some(CalendarSpec {
        months_wide: core::array::from_fn(|_| c.str()),
        months_abbr: core::array::from_fn(|_| c.str()),
        days_wide: core::array::from_fn(|_| c.str()),
        days_abbr: core::array::from_fn(|_| c.str()),
        am: c.str(),
        pm: c.str(),
        date: core::array::from_fn(|_| c.str()),
        time: core::array::from_fn(|_| c.str()),
        datetime: core::array::from_fn(|_| c.str()),
        months_narrow: core::array::from_fn(|_| c.str()),
        days_narrow: core::array::from_fn(|_| c.str()),
        eras_wide: core::array::from_fn(|_| c.str()),
        eras_abbr: core::array::from_fn(|_| c.str()),
        eras_narrow: core::array::from_fn(|_| c.str()),
        day_periods_wide: core::array::from_fn(|_| c.opt()),
        day_periods_abbr: core::array::from_fn(|_| c.opt()),
        day_periods_narrow: core::array::from_fn(|_| c.opt()),
        day_period_rules: c.dp_rules(),
        datetime_at: core::array::from_fn(|_| c.str()),
    })
}
