//! Embedded CLDR locale tables (`no_std`, no `alloc`).
//!
//! The locale formatter data (number symbols/patterns, list connectors,
//! relative-time strings, currency symbols) is generated by the offline codegen
//! into flat binary blobs committed under `src/cldr/` and embedded here with
//! [`include_bytes!`]. Because the data is just bytes, this layer has no
//! dependency on the (alloc-only) formatter runtime types and compiles in every
//! configuration; only the formatting functions that build `String`s need
//! `alloc`.
//!
//! Blob layout (little-endian): `[u16 count]` then `count` records of
//! `[u8 key_len][key][u16 payload_len][payload]`. Within a payload a string is
//! `[u8 len][bytes]` and an optional string uses a leading `0xFF` for `None`.
//!
//! The whole module is `no_std`/no-`alloc` and always compiled; its accessors
//! are unused when the (alloc-gated) formatters are not built.
#![allow(dead_code)]

// ---- Shared formatter record types (plain data, borrowing from the blobs). ----

/// A resolved CLDR number pattern (affixes + grouping / fraction-digit counts).
#[derive(Debug, Clone, Copy)]
pub struct Pattern {
    /// Literal text before the number.
    pub prefix: &'static str,
    /// Literal text after the number (for percent/currency, the sign/symbol).
    pub suffix: &'static str,
    /// Minimum integer digits.
    pub min_int: u8,
    /// Minimum fraction digits.
    pub min_frac: u8,
    /// Maximum fraction digits.
    pub max_frac: u8,
    /// Primary (rightmost) grouping size, or 0 for no grouping.
    pub primary_group: u8,
    /// Secondary grouping size (e.g. 2 for Indian `#,##,##0`).
    pub secondary_group: u8,
}

/// The number symbols and patterns for one locale.
#[derive(Debug, Clone, Copy)]
pub struct NumberSpec {
    /// Decimal separator.
    pub decimal: &'static str,
    /// Grouping separator.
    pub group: &'static str,
    /// Minus sign.
    pub minus: &'static str,
    /// Plus sign.
    pub plus: &'static str,
    /// Percent sign.
    pub percent: &'static str,
    /// The standard decimal pattern.
    pub dec: Pattern,
    /// The standard percent pattern.
    pub pct: Pattern,
}

/// The four CLDR list connector patterns (each contains `{0}` and `{1}`).
#[derive(Debug, Clone, Copy)]
pub struct ListPatterns {
    /// Joins the first two items of a 3+ list.
    pub start: &'static str,
    /// Joins an accumulated head with the next middle item.
    pub middle: &'static str,
    /// Joins the accumulated head with the final item.
    pub end: &'static str,
    /// Joins exactly two items.
    pub two: &'static str,
}

/// The list patterns for one locale (both styles).
#[derive(Debug, Clone, Copy)]
pub struct ListSpec {
    /// Conjunction ("and") patterns.
    pub and: ListPatterns,
    /// Disjunction ("or") patterns.
    pub or: ListPatterns,
}

/// CLDR relative-time strings for one unit. `past`/`future` are indexed by the
/// `PluralCategory` discriminant.
#[derive(Debug, Clone, Copy)]
pub struct RelUnit {
    /// Literal for offset −1 ("yesterday"), if any.
    pub prev: Option<&'static str>,
    /// Literal for offset 0 ("today"), if any.
    pub cur: Option<&'static str>,
    /// Literal for offset +1 ("tomorrow"), if any.
    pub next: Option<&'static str>,
    /// Past patterns ("{0} days ago") by plural category.
    pub past: [Option<&'static str>; 6],
    /// Future patterns ("in {0} days") by plural category.
    pub future: [Option<&'static str>; 6],
}

/// CLDR relative-time strings for all units of one locale.
#[derive(Debug, Clone, Copy)]
pub struct RelativeSpec {
    /// One [`RelUnit`] per relative unit (year, month, week, day, hour, minute,
    /// second).
    pub units: [RelUnit; 7],
}

// ---- Embedded blobs. ----

const NUMBERS: &[u8] = include_bytes!("cldr/numbers.bin");
const LISTS: &[u8] = include_bytes!("cldr/lists.bin");
const RELATIVE: &[u8] = include_bytes!("cldr/relative.bin");
const CURRENCY: &[u8] = include_bytes!("cldr/currency.bin");
const CURRENCY_DIGITS: &[u8] = include_bytes!("cldr/currency_digits.bin");

fn rd_u16(b: &[u8], o: usize) -> usize {
    u16::from_le_bytes([b[o], b[o + 1]]) as usize
}

/// A forward cursor over a record payload in a `'static` blob.
struct Cursor {
    b: &'static [u8],
    o: usize,
}
impl Cursor {
    fn u8(&mut self) -> u8 {
        let v = self.b[self.o];
        self.o += 1;
        v
    }
    fn str(&mut self) -> &'static str {
        let n = self.u8() as usize;
        let s = &self.b[self.o..self.o + n];
        self.o += n;
        core::str::from_utf8(s).unwrap_or("")
    }
    fn opt(&mut self) -> Option<&'static str> {
        if self.b[self.o] == 0xFF {
            self.o += 1;
            None
        } else {
            Some(self.str())
        }
    }
    fn pattern(&mut self) -> Pattern {
        Pattern {
            prefix: self.str(),
            suffix: self.str(),
            min_int: self.u8(),
            min_frac: self.u8(),
            max_frac: self.u8(),
            primary_group: self.u8(),
            secondary_group: self.u8(),
        }
    }
}

/// Locate the record for `key` and return a cursor at its payload.
fn find(blob: &'static [u8], key: &str) -> Option<Cursor> {
    let count = rd_u16(blob, 0);
    let mut o = 2;
    for _ in 0..count {
        let klen = blob[o] as usize;
        o += 1;
        let k = &blob[o..o + klen];
        o += klen;
        let plen = rd_u16(blob, o);
        o += 2;
        if k == key.as_bytes() {
            return Some(Cursor { b: blob, o });
        }
        o += plen;
    }
    None
}

/// Number symbols + patterns for an exact (lowercased) locale key.
pub(crate) fn number_spec(lang: &str) -> Option<NumberSpec> {
    let mut c = find(NUMBERS, lang)?;
    Some(NumberSpec {
        decimal: c.str(),
        group: c.str(),
        minus: c.str(),
        plus: c.str(),
        percent: c.str(),
        dec: c.pattern(),
        pct: c.pattern(),
    })
}

fn list_patterns(c: &mut Cursor) -> ListPatterns {
    ListPatterns {
        start: c.str(),
        middle: c.str(),
        end: c.str(),
        two: c.str(),
    }
}

/// List connector patterns for an exact (lowercased) locale key.
pub(crate) fn list_spec(lang: &str) -> Option<ListSpec> {
    let mut c = find(LISTS, lang)?;
    Some(ListSpec {
        and: list_patterns(&mut c),
        or: list_patterns(&mut c),
    })
}

/// Relative-time strings for an exact (lowercased) locale key.
pub(crate) fn relative_spec(lang: &str) -> Option<RelativeSpec> {
    let mut c = find(RELATIVE, lang)?;
    let units = core::array::from_fn(|_| RelUnit {
        prev: c.opt(),
        cur: c.opt(),
        next: c.opt(),
        past: core::array::from_fn(|_| c.opt()),
        future: core::array::from_fn(|_| c.opt()),
    });
    Some(RelativeSpec { units })
}

/// Standard currency pattern for an exact (lowercased) locale key.
pub(crate) fn currency_pattern(lang: &str) -> Option<Pattern> {
    let mut c = find(CURRENCY, lang)?;
    Some(c.pattern())
}

/// Currency symbol for `code` in `lang` (exact lowercased key), if present.
pub(crate) fn currency_symbol(lang: &str, code: &str) -> Option<&'static str> {
    let mut c = find(CURRENCY, lang)?;
    let _ = c.pattern();
    let n = c.u8();
    for _ in 0..n {
        let cd = c.str();
        let sym = c.str();
        if cd == code {
            return Some(sym);
        }
    }
    None
}

/// Default fraction digits for a currency code (2 if unknown).
pub(crate) fn currency_digits(code: &str) -> u8 {
    match find(CURRENCY_DIGITS, code) {
        Some(mut c) => c.u8(),
        None => 2,
    }
}
